// <auto-generated />
using System;
using CrudCarros.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CrudCarros.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429015955_inicio")]
    partial class inicio
    {
    }
}
